### ISSUE TITLE
Merging arrays of dicts?

### ISSUE THREAD

**Issue by phybros** [zerwes/hiyapyco#25] opened 2017-07-06 16:16 UTC
Hi, I had some yaml files with an array of dicts in it, and I'm confused how hiyapyco is supposed to behave in this scenario. Not sure if it's a bug or not.

base.yml

```yaml
key_one: 1
key_two: 2
array_of_dicts:
- dict_key_one: a
  dict_key_two: b
  dict_key_three: c
- dict_key_one: a1
  dict_key_two: b1
  dict_key_three: c1
```

layer.yml

```yaml
key_two: 2222
array_of_dicts:
- dict_key_one: a2
  dict_key_two: b2
  dict_key_three: c2
```

merge.py

```py
import hiyapyco

CONF = hiyapyco.load("base.yml", "layer.yml", method=hiyapyco.METHOD_MERGE)
print hiyapyco.dump(CONF)
```

result:

```yaml
key_one: 1
key_two: 2222
array_of_dicts:
- {dict_key_one: a2, dict_key_two: b2, dict_key_three: c2}
- {dict_key_one: a1, dict_key_two: b1, dict_key_three: c1}
```

I thought it would have produced:

```yaml
key_one: 1
key_two: 2222
array_of_dicts:
- {dict_key_one: a, dict_key_two: b, dict_key_three: c}
- {dict_key_one: a1, dict_key_two: b1, dict_key_three: c1}
- {dict_key_one: a2, dict_key_two: b2, dict_key_three: c2}
```

Is this a bug?

**Comment by phybros** [comment] 2017-07-06 16:32
I suppose the yaml-y way to describe this structure is a List of Maps, rather than an array of dicts, but my question stands

**Comment by zerwes** [comment] 2017-07-06 21:45
Not a bug ... feature :-)
While merging **array_of_dicts** it detects a matching key in the first dict and merges them!
So you get the result: first item in list merged and the second one unchanged.

A list of dicts is really a hard topic and I spend quite some time on the merge of this type.
I assume the expected result differs from structure to structure. And indeed, I think this is not a ideal structure to describe data.

For the case you do not like the merge method to be too clever, I have implemented a boolean kwarg **mergelists**. It defaults to true in order to keep the original behavior.

see: examples/issue25.py

`base = """
key_one: 1
key_two: 2
array_of_dicts:
- dict_key_one: a
  dict_key_two: b
  dict_key_three: c
- dict_key_one: a1
  dict_key_two: b1
  dict_key_three: c1
"""
layer = """
key_two: 2222
array_of_dicts:
- dict_key_one: a2
  dict_key_two: b2
  dict_key_three: c2
"""


CONF = hiyapyco.load([base, layer], method=hiyapyco.METHOD_MERGE)
print hiyapyco.dump(CONF)

print "... using mergelists=False ..."
CONF = hiyapyco.load([base, layer], method=hiyapyco.METHOD_MERGE, mergelists=False)
print hiyapyco.dump(CONF)`

this will give you:
`key_one: 1
key_two: 2222
array_of_dicts:
- {dict_key_one: a2, dict_key_two: b2, dict_key_three: c2}
- {dict_key_one: a1, dict_key_two: b1, dict_key_three: c1}

... using mergelists=False ...
key_one: 1
key_two: 2222
array_of_dicts:
- {dict_key_one: a, dict_key_two: b, dict_key_three: c}
- {dict_key_one: a1, dict_key_two: b1, dict_key_three: c1}
- {dict_key_one: a2, dict_key_two: b2, dict_key_three: c2}`

Hope the explanation was somehow clear and the fix helps.

**Closed** 2017-07-06 21:47 UTC

**Comment by phybros** [comment] 2017-07-07 13:14
@zerwes amazing! Thank you so much 👏

**Comment by zerwes** [comment] 2017-07-07 20:35
Usually instantly ... but I had some unexpected issues (https://packaging.python.org/guides/migrating-to-pypi-org/#uploading) and therefore disabled the pypi release yesterday.
fixed it and caught up with the pypi release right now.
